version: "3.3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - flask-data:/app/data
    networks:
      - rede-estudo

volumes:
  flask-data:

networks:
  rede-estudo:


